#[derive(Clone, Copy, Debug)]
pub struct Location {
    pub id: &'static str,
    pub label: &'static str,
    pub country: &'static str,
    pub city: &'static str,
    pub host: &'static str,
}

// Country catalog follows Surfshark's current public server-country list.
// A blank host means the country is listed by Surfshark, but we do not bundle
// an unverified IKEv2 hostname for it. Never guess an endpoint: manual IKEv2
// hostnames are authoritative in the user's Surfshark Locations tab.
pub const LOCATIONS: &[Location] = &[
    Location { id: "al-tia", label: "🇦🇱 Albania · Tirana", country: "Albania", city: "Tirana", host: "al-tia.prod.surfshark.com" },
    Location { id: "dz", label: "🇩🇿 Algeria · endpoint pending", country: "Algeria", city: "Surfshark location", host: "" },
    Location { id: "ad", label: "🇦🇩 Andorra · endpoint pending", country: "Andorra", city: "Surfshark location", host: "" },
    Location { id: "ar-bua", label: "🇦🇷 Argentina · Buenos Aires", country: "Argentina", city: "Buenos Aires", host: "ar-bua.prod.surfshark.com" },
    Location { id: "am", label: "🇦🇲 Armenia · endpoint pending", country: "Armenia", city: "Surfshark location", host: "" },
    Location { id: "au-syd", label: "🇦🇺 Australia · Sydney", country: "Australia", city: "Sydney", host: "au-syd.prod.surfshark.com" },
    Location { id: "at-vie", label: "🇦🇹 Austria · Vienna", country: "Austria", city: "Vienna", host: "at-vie.prod.surfshark.com" },
    Location { id: "az-bak", label: "🇦🇿 Azerbaijan · Baku", country: "Azerbaijan", city: "Baku", host: "az-bak.prod.surfshark.com" },
    Location { id: "bs", label: "🇧🇸 Bahamas · endpoint pending", country: "Bahamas", city: "Surfshark location", host: "" },
    Location { id: "bd", label: "🇧🇩 Bangladesh · endpoint pending", country: "Bangladesh", city: "Surfshark location", host: "" },
    Location { id: "be-bru", label: "🇧🇪 Belgium · Brussels", country: "Belgium", city: "Brussels", host: "be-bru.prod.surfshark.com" },
    Location { id: "bz", label: "🇧🇿 Belize · endpoint pending", country: "Belize", city: "Surfshark location", host: "" },
    Location { id: "bt", label: "🇧🇹 Bhutan · endpoint pending", country: "Bhutan", city: "Surfshark location", host: "" },
    Location { id: "bo", label: "🇧🇴 Bolivia · endpoint pending", country: "Bolivia", city: "Surfshark location", host: "" },
    Location { id: "ba-sjj", label: "🇧🇦 Bosnia & Herzegovina · Sarajevo", country: "Bosnia & Herzegovina", city: "Sarajevo", host: "ba-sjj.prod.surfshark.com" },
    Location { id: "br-sao", label: "🇧🇷 Brazil · São Paulo", country: "Brazil", city: "São Paulo", host: "br-sao.prod.surfshark.com" },
    Location { id: "bn", label: "🇧🇳 Brunei · endpoint pending", country: "Brunei", city: "Surfshark location", host: "" },
    Location { id: "bg-sof", label: "🇧🇬 Bulgaria · Sofia", country: "Bulgaria", city: "Sofia", host: "bg-sof.prod.surfshark.com" },
    Location { id: "kh", label: "🇰🇭 Cambodia · endpoint pending", country: "Cambodia", city: "Surfshark location", host: "" },
    Location { id: "ca-tor", label: "🇨🇦 Canada · Toronto", country: "Canada", city: "Toronto", host: "ca-tor.prod.surfshark.com" },
    Location { id: "cl-san", label: "🇨🇱 Chile · Santiago", country: "Chile", city: "Santiago", host: "cl-san.prod.surfshark.com" },
    Location { id: "co-bog", label: "🇨🇴 Colombia · Bogotá", country: "Colombia", city: "Bogotá", host: "co-bog.prod.surfshark.com" },
    Location { id: "cr-sjn", label: "🇨🇷 Costa Rica · San José", country: "Costa Rica", city: "San José", host: "cr-sjn.prod.surfshark.com" },
    Location { id: "hr-zag", label: "🇭🇷 Croatia · Zagreb", country: "Croatia", city: "Zagreb", host: "hr-zag.prod.surfshark.com" },
    Location { id: "cy-nic", label: "🇨🇾 Cyprus · Nicosia", country: "Cyprus", city: "Nicosia", host: "cy-nic.prod.surfshark.com" },
    Location { id: "cz-prg", label: "🇨🇿 Czech Republic · Prague", country: "Czech Republic", city: "Prague", host: "cz-prg.prod.surfshark.com" },
    Location { id: "dk-cph", label: "🇩🇰 Denmark · Copenhagen", country: "Denmark", city: "Copenhagen", host: "dk-cph.prod.surfshark.com" },
    Location { id: "ec", label: "🇪🇨 Ecuador · endpoint pending", country: "Ecuador", city: "Surfshark location", host: "" },
    Location { id: "eg", label: "🇪🇬 Egypt · endpoint pending", country: "Egypt", city: "Surfshark location", host: "" },
    Location { id: "ee-tll", label: "🇪🇪 Estonia · Tallinn", country: "Estonia", city: "Tallinn", host: "ee-tll.prod.surfshark.com" },
    Location { id: "fi-hel", label: "🇫🇮 Finland · Helsinki", country: "Finland", city: "Helsinki", host: "fi-hel.prod.surfshark.com" },
    Location { id: "fr-par", label: "🇫🇷 France · Paris", country: "France", city: "Paris", host: "fr-par.prod.surfshark.com" },
    Location { id: "ge-tbs", label: "🇬🇪 Georgia · Tbilisi", country: "Georgia", city: "Tbilisi", host: "ge-tbs.prod.surfshark.com" },
    Location { id: "de-ber", label: "🇩🇪 Germany · Berlin", country: "Germany", city: "Berlin", host: "de-ber.prod.surfshark.com" },
    Location { id: "gh", label: "🇬🇭 Ghana · endpoint pending", country: "Ghana", city: "Surfshark location", host: "" },
    Location { id: "gr-ath", label: "🇬🇷 Greece · Athens", country: "Greece", city: "Athens", host: "gr-ath.prod.surfshark.com" },
    Location { id: "gl", label: "🇬🇱 Greenland · endpoint pending", country: "Greenland", city: "Surfshark location", host: "" },
    Location { id: "hk-hkg", label: "🇭🇰 Hong Kong · Hong Kong", country: "Hong Kong", city: "Hong Kong", host: "hk-hkg.prod.surfshark.com" },
    Location { id: "hu-bud", label: "🇭🇺 Hungary · Budapest", country: "Hungary", city: "Budapest", host: "hu-bud.prod.surfshark.com" },
    Location { id: "is-rkv", label: "🇮🇸 Iceland · Reykjavík", country: "Iceland", city: "Reykjavík", host: "is-rkv.prod.surfshark.com" },
    Location { id: "in-mum", label: "🇮🇳 India · Mumbai", country: "India", city: "Mumbai", host: "in-mum.prod.surfshark.com" },
    Location { id: "id-jak", label: "🇮🇩 Indonesia · Jakarta", country: "Indonesia", city: "Jakarta", host: "id-jak.prod.surfshark.com" },
    Location { id: "ie-dub", label: "🇮🇪 Ireland · Dublin", country: "Ireland", city: "Dublin", host: "ie-dub.prod.surfshark.com" },
    Location { id: "im", label: "🇮🇲 Isle of Man · endpoint pending", country: "Isle of Man", city: "Surfshark location", host: "" },
    Location { id: "il-tlv", label: "🇮🇱 Israel · Tel Aviv", country: "Israel", city: "Tel Aviv", host: "il-tlv.prod.surfshark.com" },
    Location { id: "it-mil", label: "🇮🇹 Italy · Milan", country: "Italy", city: "Milan", host: "it-mil.prod.surfshark.com" },
    Location { id: "jp-tok", label: "🇯🇵 Japan · Tokyo", country: "Japan", city: "Tokyo", host: "jp-tok.prod.surfshark.com" },
    Location { id: "kz-ura", label: "🇰🇿 Kazakhstan · Oral", country: "Kazakhstan", city: "Oral", host: "kz-ura.prod.surfshark.com" },
    Location { id: "la", label: "🇱🇦 Laos · endpoint pending", country: "Laos", city: "Surfshark location", host: "" },
    Location { id: "lv-rig", label: "🇱🇻 Latvia · Riga", country: "Latvia", city: "Riga", host: "lv-rig.prod.surfshark.com" },
    Location { id: "li", label: "🇱🇮 Liechtenstein · endpoint pending", country: "Liechtenstein", city: "Surfshark location", host: "" },
    Location { id: "lt", label: "🇱🇹 Lithuania · endpoint pending", country: "Lithuania", city: "Surfshark location", host: "" },
    Location { id: "lu-ste", label: "🇱🇺 Luxembourg · Luxembourg", country: "Luxembourg", city: "Luxembourg", host: "lu-ste.prod.surfshark.com" },
    Location { id: "mo", label: "🇲🇴 Macau SAR China · endpoint pending", country: "Macau SAR China", city: "Surfshark location", host: "" },
    Location { id: "my-kul", label: "🇲🇾 Malaysia · Kuala Lumpur", country: "Malaysia", city: "Kuala Lumpur", host: "my-kul.prod.surfshark.com" },
    Location { id: "mt-mla", label: "🇲🇹 Malta · Valletta", country: "Malta", city: "Valletta", host: "mt-mla.prod.surfshark.com" },
    Location { id: "ma", label: "🇲🇦 Morocco · endpoint pending", country: "Morocco", city: "Surfshark location", host: "" },
    Location { id: "mx-mex", label: "🇲🇽 Mexico · Mexico City", country: "Mexico", city: "Mexico City", host: "mx-mex.prod.surfshark.com" },
    Location { id: "md-chi", label: "🇲🇩 Moldova · Chișinău", country: "Moldova", city: "Chișinău", host: "md-chi.prod.surfshark.com" },
    Location { id: "mc", label: "🇲🇨 Monaco · endpoint pending", country: "Monaco", city: "Surfshark location", host: "" },
    Location { id: "mn", label: "🇲🇳 Mongolia · endpoint pending", country: "Mongolia", city: "Surfshark location", host: "" },
    Location { id: "me", label: "🇲🇪 Montenegro · endpoint pending", country: "Montenegro", city: "Surfshark location", host: "" },
    Location { id: "mm", label: "🇲🇲 Myanmar (Burma) · endpoint pending", country: "Myanmar (Burma)", city: "Surfshark location", host: "" },
    Location { id: "np", label: "🇳🇵 Nepal · endpoint pending", country: "Nepal", city: "Surfshark location", host: "" },
    Location { id: "nl-ams", label: "🇳🇱 Netherlands · Amsterdam", country: "Netherlands", city: "Amsterdam", host: "nl-ams.prod.surfshark.com" },
    Location { id: "nz-akl", label: "🇳🇿 New Zealand · Auckland", country: "New Zealand", city: "Auckland", host: "nz-akl.prod.surfshark.com" },
    Location { id: "ng-lag", label: "🇳🇬 Nigeria · Lagos", country: "Nigeria", city: "Lagos", host: "ng-lag.prod.surfshark.com" },
    Location { id: "mk-skp", label: "🇲🇰 North Macedonia · Skopje", country: "North Macedonia", city: "Skopje", host: "mk-skp.prod.surfshark.com" },
    Location { id: "no-osl", label: "🇳🇴 Norway · Oslo", country: "Norway", city: "Oslo", host: "no-osl.prod.surfshark.com" },
    Location { id: "pk", label: "🇵🇰 Pakistan · endpoint pending", country: "Pakistan", city: "Surfshark location", host: "" },
    Location { id: "pa-pac", label: "🇵🇦 Panama · Panama City", country: "Panama", city: "Panama City", host: "pa-pac.prod.surfshark.com" },
    Location { id: "py", label: "🇵🇾 Paraguay · endpoint pending", country: "Paraguay", city: "Surfshark location", host: "" },
    Location { id: "pe-lim", label: "🇵🇪 Peru · Lima", country: "Peru", city: "Lima", host: "pe-lim.prod.surfshark.com" },
    Location { id: "ph-mnl", label: "🇵🇭 Philippines · Manila", country: "Philippines", city: "Manila", host: "ph-mnl.prod.surfshark.com" },
    Location { id: "pl-waw", label: "🇵🇱 Poland · Warsaw", country: "Poland", city: "Warsaw", host: "pl-waw.prod.surfshark.com" },
    Location { id: "pt-lis", label: "🇵🇹 Portugal · Lisbon", country: "Portugal", city: "Lisbon", host: "pt-lis.prod.surfshark.com" },
    Location { id: "pr", label: "🇵🇷 Puerto Rico · endpoint pending", country: "Puerto Rico", city: "Surfshark location", host: "" },
    Location { id: "ro-buc", label: "🇷🇴 Romania · Bucharest", country: "Romania", city: "Bucharest", host: "ro-buc.prod.surfshark.com" },
    Location { id: "sa", label: "🇸🇦 Saudi Arabia · endpoint pending", country: "Saudi Arabia", city: "Surfshark location", host: "" },
    Location { id: "rs-beg", label: "🇷🇸 Serbia · Belgrade", country: "Serbia", city: "Belgrade", host: "rs-beg.prod.surfshark.com" },
    Location { id: "sg-sng", label: "🇸🇬 Singapore · Singapore", country: "Singapore", city: "Singapore", host: "sg-sng.prod.surfshark.com" },
    Location { id: "sk-bts", label: "🇸🇰 Slovakia · Bratislava", country: "Slovakia", city: "Bratislava", host: "sk-bts.prod.surfshark.com" },
    Location { id: "si-lju", label: "🇸🇮 Slovenia · Ljubljana", country: "Slovenia", city: "Ljubljana", host: "si-lju.prod.surfshark.com" },
    Location { id: "za-jnb", label: "🇿🇦 South Africa · Johannesburg", country: "South Africa", city: "Johannesburg", host: "za-jnb.prod.surfshark.com" },
    Location { id: "kr-seo", label: "🇰🇷 South Korea · Seoul", country: "South Korea", city: "Seoul", host: "kr-seo.prod.surfshark.com" },
    Location { id: "es-mad", label: "🇪🇸 Spain · Madrid", country: "Spain", city: "Madrid", host: "es-mad.prod.surfshark.com" },
    Location { id: "lk", label: "🇱🇰 Sri Lanka · endpoint pending", country: "Sri Lanka", city: "Surfshark location", host: "" },
    Location { id: "se-sto", label: "🇸🇪 Sweden · Stockholm", country: "Sweden", city: "Stockholm", host: "se-sto.prod.surfshark.com" },
    Location { id: "ch-zur", label: "🇨🇭 Switzerland · Zurich", country: "Switzerland", city: "Zurich", host: "ch-zur.prod.surfshark.com" },
    Location { id: "tw-tai", label: "🇹🇼 Taiwan · Taichung City", country: "Taiwan", city: "Taichung City", host: "tw-tai.prod.surfshark.com" },
    Location { id: "th-bkk", label: "🇹🇭 Thailand · Bangkok", country: "Thailand", city: "Bangkok", host: "th-bkk.prod.surfshark.com" },
    Location { id: "tr-ist", label: "🇹🇷 Turkey · Istanbul", country: "Turkey", city: "Istanbul", host: "tr-ist.prod.surfshark.com" },
    Location { id: "ua-iev", label: "🇺🇦 Ukraine · Kyiv", country: "Ukraine", city: "Kyiv", host: "ua-iev.prod.surfshark.com" },
    Location { id: "ae-dub", label: "🇦🇪 United Arab Emirates · Dubai", country: "United Arab Emirates", city: "Dubai", host: "ae-dub.prod.surfshark.com" },
    Location { id: "uk-lon", label: "🇬🇧 United Kingdom · London", country: "United Kingdom", city: "London", host: "uk-lon.prod.surfshark.com" },
    Location { id: "us-nyc", label: "🇺🇸 United States · New York", country: "United States", city: "New York", host: "us-nyc.prod.surfshark.com" },
    Location { id: "uy", label: "🇺🇾 Uruguay · endpoint pending", country: "Uruguay", city: "Surfshark location", host: "" },
    Location { id: "uz", label: "🇺🇿 Uzbekistan · endpoint pending", country: "Uzbekistan", city: "Surfshark location", host: "" },
    Location { id: "ve", label: "🇻🇪 Venezuela · endpoint pending", country: "Venezuela", city: "Surfshark location", host: "" },
    Location { id: "vn-hcm", label: "🇻🇳 Vietnam · Ho Chi Minh City", country: "Vietnam", city: "Ho Chi Minh City", host: "vn-hcm.prod.surfshark.com" },

    // Extra cities for countries where useful generic IKEv2 hostnames are known.
    Location { id: "de-fra", label: "🇩🇪 Germany · Frankfurt", country: "Germany", city: "Frankfurt", host: "de-fra.prod.surfshark.com" },
    Location { id: "ca-van", label: "🇨🇦 Canada · Vancouver", country: "Canada", city: "Vancouver", host: "ca-van.prod.surfshark.com" },
    Location { id: "us-lax", label: "🇺🇸 United States · Los Angeles", country: "United States", city: "Los Angeles", host: "us-lax.prod.surfshark.com" },
    Location { id: "fr-bod", label: "🇫🇷 France · Bordeaux", country: "France", city: "Bordeaux", host: "fr-bod.prod.surfshark.com" },
    Location { id: "it-rom", label: "🇮🇹 Italy · Rome", country: "Italy", city: "Rome", host: "it-rom.prod.surfshark.com" },
    Location { id: "pl-gdn", label: "🇵🇱 Poland · Gdańsk", country: "Poland", city: "Gdańsk", host: "pl-gdn.prod.surfshark.com" },
    Location { id: "pt-opo", label: "🇵🇹 Portugal · Porto", country: "Portugal", city: "Porto", host: "pt-opo.prod.surfshark.com" },
    Location { id: "es-bcn", label: "🇪🇸 Spain · Barcelona", country: "Spain", city: "Barcelona", host: "es-bcn.prod.surfshark.com" },
    Location { id: "uk-man", label: "🇬🇧 United Kingdom · Manchester", country: "United Kingdom", city: "Manchester", host: "uk-man.prod.surfshark.com" },
    Location { id: "au-mel", label: "🇦🇺 Australia · Melbourne", country: "Australia", city: "Melbourne", host: "au-mel.prod.surfshark.com" },
];

pub fn by_id(id: &str) -> Option<Location> {
    LOCATIONS.iter().copied().find(|item| item.id == id)
}

pub fn by_host(host: &str) -> Option<Location> {
    if host.is_empty() {
        return None;
    }
    LOCATIONS.iter().copied().find(|item| item.host == host)
}
