mod bundled_endpoints;
mod locations;

use adw::prelude::*;
use bundled_endpoints::for_host as bundled_for_host;
use gtk::{glib, Orientation};
use locations::{by_id, LOCATIONS};
use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::rc::Rc;
use std::sync::mpsc;
use std::thread;
use std::time::Duration;

const RESTRICTED_CONNECT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../scripts/restricted-ikev2-connect.sh");
const RESTRICTED_DISCONNECT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../scripts/restricted-ikev2-disconnect.sh");
const RESTRICTED_STATE: &str = "/run/milmit-surfshark/restricted.state";
const LIVE_STATE: &str = "/run/milmit-surfshark/live.state";
const HELPER: &str = "/usr/libexec/milmit-surfshark-helper";
const DEFAULT_DNS: &str = "162.252.172.57,149.154.159.92";

#[derive(Clone)]
struct AppSettings {
    mss: u32,
    dns: String,
    hotspot_vpn: bool,
    hotspot_iface: String,
    recover_network: bool,
    kill_switch: bool,
    routing_mode: String,
    hotspot_vpn_macs: String,
    hotspot_direct_macs: String,
}
impl Default for AppSettings {
    fn default() -> Self { Self { mss:1200, dns:DEFAULT_DNS.into(), hotspot_vpn:true, hotspot_iface:"auto".into(), recover_network:true, kill_switch:true, routing_mode:"vpn_all".into(), hotspot_vpn_macs:String::new(), hotspot_direct_macs:String::new() } }
}

#[derive(Debug)]
enum Event {
    Busy(String), Log(String,String), Connected(String,String), Disconnected, Failed(String), Tool(String,String), PingResults(Vec<(String,Option<u32>)>),
}

fn run(cmd:&str,args:&[&str])->String {
    match Command::new(cmd).args(args).output() {
        Ok(out)=>{ let mut s=String::from_utf8_lossy(&out.stdout).to_string(); if !out.stderr.is_empty(){if !s.is_empty(){s.push('\n');}s.push_str(&String::from_utf8_lossy(&out.stderr));} s.trim().to_string() },
        Err(e)=>format!("Failed to run {cmd}: {e}")
    }
}
fn file_value(path:&str,key:&str)->Option<String>{ let text=fs::read_to_string(path).ok()?; text.lines().find_map(|l|{let(k,v)=l.split_once('=')?;(k==key).then(||v.trim().to_string())}).filter(|v|!v.is_empty()) }
fn state_value(key:&str)->Option<String>{file_value(RESTRICTED_STATE,key)}
fn live_value(key:&str)->Option<String>{file_value(LIVE_STATE,key)}
fn active()->bool{ state_value("VIRTUAL_IP").map(|v|run("ip",&["-4","addr","show"]).contains(&v)).unwrap_or(false) }
fn config_dir()->PathBuf{ std::env::var("XDG_CONFIG_HOME").map(PathBuf::from).or_else(|_|std::env::var("HOME").map(|h|PathBuf::from(h).join(".config"))).unwrap_or_else(|_|PathBuf::from(".")).join("milmit-surfshark") }
fn username_path()->PathBuf{config_dir().join("username")}
fn settings_path()->PathBuf{config_dir().join("settings.conf")}
fn saved_username()->Option<String>{fs::read_to_string(username_path()).ok().map(|v|v.trim().to_string()).filter(|v|!v.is_empty())}
fn save_username(v:&str){let p=username_path();if let Some(x)=p.parent(){let _=fs::create_dir_all(x);}let _=fs::write(p,v);}
fn normalize_mac_csv(v:&str)->String{let mut out=Vec::<String>::new();for x in v.split(','){let m=x.trim().to_ascii_uppercase();if !m.is_empty()&&!out.contains(&m){out.push(m)}}out.join(",")}
fn load_settings()->AppSettings{let mut s=AppSettings::default();if let Ok(t)=fs::read_to_string(settings_path()){for l in t.lines(){if let Some((k,v))=l.split_once('='){match k{"mss"=>if let Ok(n)=v.parse::<u32>(){if(900..=1400).contains(&n){s.mss=n}},"dns"=>if !v.is_empty(){s.dns=v.into()},"hotspot_vpn"=>s.hotspot_vpn=v=="1","hotspot_iface"=>if !v.is_empty(){s.hotspot_iface=v.into()},"recover_network"=>s.recover_network=v=="1","kill_switch"=>s.kill_switch=v=="1","routing_mode"=>if matches!(v,"vpn_all"|"iran_direct"){s.routing_mode=v.into()},"hotspot_vpn_macs"=>s.hotspot_vpn_macs=normalize_mac_csv(v),"hotspot_direct_macs"=>s.hotspot_direct_macs=normalize_mac_csv(v),_=>{}}}}}s}
fn save_settings(s:&AppSettings){let p=settings_path();if let Some(x)=p.parent(){let _=fs::create_dir_all(x);}let text=format!("mss={}\ndns={}\nhotspot_vpn={}\nhotspot_iface={}\nrecover_network={}\nkill_switch={}\nrouting_mode={}\nhotspot_vpn_macs={}\nhotspot_direct_macs={}\n",s.mss,s.dns,s.hotspot_vpn as u8,s.hotspot_iface,s.recover_network as u8,s.kill_switch as u8,s.routing_mode,s.hotspot_vpn_macs,s.hotspot_direct_macs);let _=fs::write(p,text);}

fn restricted_candidates(host:&str)->Vec<String>{let mut o=Vec::new();if host=="ee-tll.prod.surfshark.com"{o.push("185.174.159.123".into())}for ip in bundled_for_host(host){if !o.iter().any(|v|v==ip){o.push((*ip).into())}}o}
fn restricted_connect(endpoint:&str,username:&str,password:&str,s:&AppSettings)->(bool,String){let mss=s.mss.to_string();let hotspot=if s.hotspot_vpn{"1"}else{"0"};let recover=if s.recover_network{"1"}else{"0"};let kill=if s.kill_switch{"1"}else{"0"};let mut c=match Command::new("pkexec").arg("bash").arg(RESTRICTED_CONNECT).arg(endpoint).arg(username).arg(&mss).arg(&s.dns).arg(hotspot).arg(recover).arg(&s.hotspot_iface).arg(kill).arg(&s.routing_mode).arg(&s.hotspot_vpn_macs).arg(&s.hotspot_direct_macs).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn(){Ok(c)=>c,Err(e)=>return(false,e.to_string())};if let Some(stdin)=c.stdin.as_mut(){let _=writeln!(stdin,"{password}");}match c.wait_with_output(){Ok(o)=>{let mut t=String::from_utf8_lossy(&o.stdout).to_string();t.push_str(&String::from_utf8_lossy(&o.stderr));(o.status.success()&&t.contains("Data-path test: OK"),t)},Err(e)=>(false,e.to_string())}}
fn disconnect()->String{run("pkexec",&["bash",RESTRICTED_DISCONNECT])}
fn helper(args:&[&str])->String{let mut c=Command::new("pkexec");c.arg(HELPER).args(args);match c.output(){Ok(o)=>{let mut t=String::from_utf8_lossy(&o.stdout).to_string();if !o.stderr.is_empty(){t.push_str(&String::from_utf8_lossy(&o.stderr));}t},Err(e)=>e.to_string()}}
fn parse_colon(text:&str,key:&str)->Option<String>{text.lines().find_map(|l|{let(k,v)=l.split_once(':')?;(k.trim()==key).then(||v.trim().to_string())}).filter(|v|!v.is_empty())}
fn json_number(text:&str,key:&str)->Option<u32>{let needle=format!("\"{key}\":");let p=text.find(&needle)?+needle.len();let r=&text[p..];let n=r.trim_start().chars().take_while(|c|c.is_ascii_digit()).collect::<String>();n.parse().ok()}
fn json_string(text:&str,key:&str)->Option<String>{let needle=format!("\"{key}\":");let p=text.find(&needle)?+needle.len();let r=text[p..].trim_start();let r=r.strip_prefix('"')?;Some(r.chars().take_while(|c|*c!='"').collect())}
fn fmt_rate(raw:Option<String>)->String{let n=raw.and_then(|v|v.parse::<f64>().ok()).unwrap_or(0.0);if n>=1_048_576.0{format!("{:.1} MB/s",n/1_048_576.0)}else if n>=1024.0{format!("{:.0} KB/s",n/1024.0)}else{format!("{:.0} B/s",n)}}
fn ping_ms(host:&str)->Option<u32>{let target=if host=="ee-tll.prod.surfshark.com"{"185.174.159.123"}else{bundled_for_host(host).first().copied().unwrap_or(host)};let o=Command::new("ping").args(["-n","-c","1","-W","1",target]).output().ok()?;if !o.status.success(){return None}let t=String::from_utf8_lossy(&o.stdout);let st=t.find("time=")?+5;let r=&t[st..];let en=r.find(|c:char|c==' '||c=='\n').unwrap_or(r.len());r[..en].parse::<f64>().ok().map(|v|v.round()as u32)}
fn scan_latencies()->Vec<(String,Option<u32>)>{LOCATIONS.iter().map(|x|(x.id.to_string(),ping_ms(x.host))).collect()}

fn install_css(){let p=gtk::CssProvider::new();p.load_from_data("window{background:@window_bg_color}.shell{background:linear-gradient(145deg,alpha(@window_bg_color,.98),alpha(@view_bg_color,.92))}.sidebar{min-width:188px;padding:20px 12px;background:alpha(@card_bg_color,.58);border-right:1px solid alpha(@borders,.45)}.brand{font-size:19px;font-weight:900;letter-spacing:1px}.brand-sub{font-size:10px;opacity:.55}.nav{min-height:44px;border-radius:13px;background:transparent;box-shadow:none;padding:0 14px}.nav:hover{background:alpha(@accent_bg_color,.10)}.nav-active{background:alpha(@accent_bg_color,.17);font-weight:900}.page{padding:22px 26px 28px}.hero{padding:26px;border-radius:28px;background:linear-gradient(135deg,alpha(@accent_bg_color,.17),alpha(@card_bg_color,.72));border:1px solid alpha(@accent_bg_color,.24)}.orb{min-width:176px;min-height:176px;border-radius:999px;background:radial-gradient(circle,alpha(@accent_bg_color,.30),alpha(@accent_bg_color,.06));border:2px solid alpha(@accent_bg_color,.52);box-shadow:0 0 28px alpha(@accent_bg_color,.16)}.orb-pulse{box-shadow:0 0 46px alpha(@accent_bg_color,.30);border-color:alpha(@accent_bg_color,.82)}.orb-ok{background:radial-gradient(circle,alpha(@success_color,.28),alpha(@success_color,.05));border-color:alpha(@success_color,.58)}.orb-error{background:radial-gradient(circle,alpha(@error_color,.24),alpha(@error_color,.05));border-color:alpha(@error_color,.62)}.orb-icon{-gtk-icon-size:60px}.status{font-size:22px;font-weight:900}.sub{font-size:11px;opacity:.64}.connect{min-height:50px;min-width:210px;border-radius:999px;font-weight:900}.metric{padding:14px 16px;border-radius:16px;background:alpha(@card_bg_color,.72);border:1px solid alpha(@borders,.42)}.metric-value{font-size:16px;font-weight:900}.metric-name{font-size:9px;opacity:.58;letter-spacing:.6px}.card{padding:17px;border-radius:19px;background:alpha(@card_bg_color,.68);border:1px solid alpha(@borders,.42)}.card-title{font-size:14px;font-weight:900}.tiny{font-size:10px;opacity:.60}.pill{padding:7px 11px;border-radius:999px;background:alpha(@accent_bg_color,.12);font-size:10px;font-weight:800}.health-score{font-size:30px;font-weight:950}.danger-card{padding:17px;border-radius:19px;background:alpha(@error_color,.07);border:1px solid alpha(@error_color,.30)}entry,spinbutton,combobox button{min-height:40px;border-radius:11px}.tool{min-height:43px;border-radius:12px}.diag{font-size:11px;padding:12px}.progress trough{min-height:5px;border-radius:999px}.progress progress{min-height:5px;border-radius:999px}");if let Some(d)=gtk::gdk::Display::default(){gtk::style_context_add_provider_for_display(&d,&p,gtk::STYLE_PROVIDER_PRIORITY_APPLICATION)}}
fn title(t:&str,s:&str)->gtk::Box{let b=gtk::Box::new(Orientation::Vertical,2);b.append(&gtk::Label::builder().label(t).halign(gtk::Align::Start).css_classes(["card-title"]).build());b.append(&gtk::Label::builder().label(s).halign(gtk::Align::Start).wrap(true).css_classes(["tiny"]).build());b}
fn metric(name:&str,val:&gtk::Label)->gtk::Box{let b=gtk::Box::new(Orientation::Vertical,3);b.add_css_class("metric");b.set_hexpand(true);val.add_css_class("metric-value");b.append(val);b.append(&gtk::Label::builder().label(name).halign(gtk::Align::Start).css_classes(["metric-name"]).build());b}
fn nav_button(label:&str)->gtk::Button{let b=gtk::Button::with_label(label);b.add_css_class("nav");b.set_halign(gtk::Align::Fill);b}

fn main()->glib::ExitCode{let app=adw::Application::builder().application_id("net.milmit.SurfsharkIkev2").build();app.connect_activate(build_ui);app.run()}
fn build_ui(app:&adw::Application){
    install_css();let settings=load_settings();let is_active=active();
    let header=adw::HeaderBar::new();header.set_title_widget(Some(&adw::WindowTitle::new("MilMit Secure","Adaptive IKEv2 Protection Control Center")));

    let status_icon=gtk::Image::from_icon_name(if is_active{"network-vpn-symbolic"}else{"network-offline-symbolic"});status_icon.add_css_class("orb-icon");let orb=gtk::Box::new(Orientation::Vertical,0);orb.set_halign(gtk::Align::Center);orb.set_valign(gtk::Align::Center);orb.add_css_class("orb");if is_active{orb.add_css_class("orb-ok")}orb.append(&status_icon);
    let status=gtk::Label::builder().label(if is_active{"Protected"}else{"Ready"}).css_classes(["status"]).build();let detail=gtk::Label::builder().label(if is_active{"Encrypted IKEv2 path is active"}else{"Choose a location and start protection"}).css_classes(["sub"]).build();
    let spinner=gtk::Spinner::new();let progress=gtk::ProgressBar::new();progress.add_css_class("progress");progress.set_visible(false);
    let connect=gtk::Button::with_label("Connect securely");connect.add_css_class("suggested-action");connect.add_css_class("connect");connect.set_visible(!is_active);let disconnect_btn=gtk::Button::with_label("Disconnect");disconnect_btn.add_css_class("destructive-action");disconnect_btn.add_css_class("connect");disconnect_btn.set_visible(is_active);
    let actions=gtk::Box::new(Orientation::Horizontal,8);actions.set_halign(gtk::Align::Center);actions.append(&connect);actions.append(&disconnect_btn);
    let ip_val=gtk::Label::builder().label(state_value("PUBLIC_IP").unwrap_or_else(||"—".into())).halign(gtk::Align::Start).build();let down_val=gtk::Label::builder().label("0 B/s").halign(gtk::Align::Start).build();let up_val=gtk::Label::builder().label("0 B/s").halign(gtk::Align::Start).build();let lat_val=gtk::Label::builder().label("— ms").halign(gtk::Align::Start).build();
    let metrics=gtk::Box::new(Orientation::Horizontal,10);metrics.append(&metric("PUBLIC IP",&ip_val));metrics.append(&metric("DOWNLOAD",&down_val));metrics.append(&metric("UPLOAD",&up_val));metrics.append(&metric("LATENCY",&lat_val));
    let hero=gtk::Box::new(Orientation::Vertical,10);hero.add_css_class("hero");hero.append(&orb);hero.append(&status);hero.append(&detail);hero.append(&spinner);hero.append(&progress);hero.append(&actions);hero.append(&metrics);

    let location=gtk::ComboBoxText::new();location.set_hexpand(true);for x in LOCATIONS{location.append(Some(x.id),x.label)}location.set_active_id(Some("ee-tll"));let scan=gtk::Button::with_label("Scan latency");scan.add_css_class("tool");let lr=gtk::Box::new(Orientation::Horizontal,8);lr.append(&location);lr.append(&scan);let loc_card=gtk::Box::new(Orientation::Vertical,10);loc_card.add_css_class("card");loc_card.append(&title("Smart location","Direct-IP candidates with latency scan for restricted networks"));loc_card.append(&lr);
    let health_score=gtk::Label::builder().label("—").css_classes(["health-score"]).build();let health_state=gtk::Label::builder().label("Checking…").css_classes(["pill"]).build();let health_refresh=gtk::Button::with_label("Protection health");health_refresh.add_css_class("tool");let hrow=gtk::Box::new(Orientation::Horizontal,12);hrow.append(&health_score);hrow.append(&health_state);hrow.append(&health_refresh);let health_card=gtk::Box::new(Orientation::Vertical,9);health_card.add_css_class("card");health_card.append(&title("Protection Health","IKE + XFRM + route + exit-IP + watchdog + DNS + kill-switch evidence"));health_card.append(&hrow);
    let topo=gtk::Label::builder().label("Device  →  Linux  →  XFRM  →  Surfshark  →  Internet").wrap(true).css_classes(["pill"]).build();let topo_card=gtk::Box::new(Orientation::Vertical,8);topo_card.add_css_class("card");topo_card.append(&title("Live protected path","Topology follows the active policy route and hotspot state"));topo_card.append(&topo);
    let dashboard=gtk::Box::new(Orientation::Vertical,14);dashboard.add_css_class("page");dashboard.append(&hero);dashboard.append(&loc_card);dashboard.append(&health_card);dashboard.append(&topo_card);

    let user=gtk::Entry::builder().placeholder_text("Surfshark service username").hexpand(true).build();if let Some(u)=saved_username(){user.set_text(&u)}let pass=gtk::PasswordEntry::builder().placeholder_text("Service password · blank = saved root credential").show_peek_icon(true).hexpand(true).build();let routing=gtk::ComboBoxText::new();routing.append(Some("vpn_all"),"VPN Everything");routing.append(Some("iran_direct"),"Iran Direct · Foreign through VPN");routing.set_active_id(Some(&settings.routing_mode));let kill=gtk::CheckButton::with_label("Kill Switch · fail closed if protected route disappears");kill.set_active(settings.kill_switch);let recover=gtk::CheckButton::with_label("Auto recovery after network changes");recover.set_active(settings.recover_network);let mss=gtk::SpinButton::with_range(900.0,1400.0,10.0);mss.set_value(settings.mss as f64);let dns=gtk::Entry::builder().text(&settings.dns).hexpand(true).build();
    let cred=gtk::Box::new(Orientation::Vertical,9);cred.add_css_class("card");cred.append(&title("Credentials","Service credentials are separate from the Surfshark account login"));cred.append(&user);cred.append(&pass);let route_card=gtk::Box::new(Orientation::Vertical,9);route_card.add_css_class("card");route_card.append(&title("Routing & leak protection","Policy routing tuned for filtered/mobile networks"));route_card.append(&routing);route_card.append(&kill);route_card.append(&recover);let tune=gtk::Box::new(Orientation::Vertical,9);tune.add_css_class("card");tune.append(&title("Compatibility tuning","MSS 1200 is the verified baseline on restricted links; MTU probe can refine it"));let mr=gtk::Box::new(Orientation::Horizontal,8);mr.append(&gtk::Label::new(Some("TCP MSS")));mr.append(&mss);tune.append(&mr);tune.append(&dns);let routing_page=gtk::Box::new(Orientation::Vertical,14);routing_page.add_css_class("page");routing_page.append(&cred);routing_page.append(&route_card);routing_page.append(&tune);

    let hotspot=gtk::CheckButton::with_label("Unlisted hotspot devices use VPN");hotspot.set_active(settings.hotspot_vpn);let iface=gtk::Entry::builder().text(&settings.hotspot_iface).placeholder_text("auto or hotspot interface").build();let vpn_macs=gtk::Entry::builder().text(&settings.hotspot_vpn_macs).placeholder_text("Force VPN MACs · comma separated").build();let direct_macs=gtk::Entry::builder().text(&settings.hotspot_direct_macs).placeholder_text("Direct MACs · comma separated").build();let dev_card=gtk::Box::new(Orientation::Vertical,9);dev_card.add_css_class("card");dev_card.append(&title("Per-device hotspot policy","Direct and VPN policy lists are enforced before the default device policy"));dev_card.append(&iface);dev_card.append(&hotspot);dev_card.append(&vpn_macs);dev_card.append(&direct_macs);let manage=gtk::Button::with_label("Open visual hotspot device manager");manage.add_css_class("tool");let recent=gtk::Button::with_label("Recent Internet destinations");recent.add_css_class("tool");dev_card.append(&manage);dev_card.append(&recent);let devices_page=gtk::Box::new(Orientation::Vertical,14);devices_page.add_css_class("page");devices_page.append(&dev_card);

    let speed=gtk::Button::with_label("Speed + TTFB test");let dns_test=gtk::Button::with_label("DNS leak evidence");let mtu=gtk::Button::with_label("Adaptive MTU/MSS probe");let save_lkg=gtk::Button::with_label("Save Last Known Good");let support=gtk::Button::with_label("Create redacted support bundle");for b in [&speed,&dns_test,&mtu,&save_lkg,&support]{b.add_css_class("tool")};let grid=gtk::Grid::builder().row_spacing(8).column_spacing(8).build();grid.attach(&speed,0,0,1,1);grid.attach(&dns_test,1,0,1,1);grid.attach(&mtu,0,1,1,1);grid.attach(&save_lkg,1,1,1,1);grid.attach(&support,0,2,2,1);let tool_card=gtk::Box::new(Orientation::Vertical,10);tool_card.add_css_class("card");tool_card.append(&title("Adaptive protection tools","Bounded diagnostics inspired by the router engine: no blind route changes"));tool_card.append(&grid);
    let route_target=gtk::Entry::builder().placeholder_text("Route Tester · domain, IP or URL").hexpand(true).build();let route_test=gtk::Button::with_label("Test route");route_test.add_css_class("tool");let rr=gtk::Box::new(Orientation::Horizontal,8);rr.append(&route_target);rr.append(&route_test);let rt_card=gtk::Box::new(Orientation::Vertical,9);rt_card.add_css_class("card");rt_card.append(&title("Route Tester","Shows intended VPN/Direct path vs the actual Linux route; Iran cache aware"));rt_card.append(&rr);
    let emergency=gtk::Button::with_label("STOP EVERYTHING");emergency.add_css_class("destructive-action");emergency.add_css_class("tool");let danger=gtk::Box::new(Orientation::Vertical,9);danger.add_css_class("danger-card");danger.append(&title("Emergency stop","Removes MilMit-owned XFRM/policy routing and disconnects the tunnel"));danger.append(&emergency);let tools_page=gtk::Box::new(Orientation::Vertical,14);tools_page.add_css_class("page");tools_page.append(&tool_card);tools_page.append(&rt_card);tools_page.append(&danger);

    let text=gtk::TextView::builder().editable(false).monospace(true).wrap_mode(gtk::WrapMode::WordChar).css_classes(["diag"]).build();let buffer=text.buffer();buffer.set_text("MilMit Secure · operation monitor\n");let scroll=gtk::ScrolledWindow::builder().vexpand(true).child(&text).build();let diag_card=gtk::Box::new(Orientation::Vertical,9);diag_card.add_css_class("card");diag_card.append(&title("Operation Monitor","Connection logs, diagnostics, route tests and tool output stream here"));diag_card.append(&scroll);let diagnostics=gtk::Box::new(Orientation::Vertical,14);diagnostics.add_css_class("page");diagnostics.append(&diag_card);

    let stack=gtk::Stack::new();stack.set_transition_type(gtk::StackTransitionType::SlideLeftRight);stack.set_transition_duration(300);stack.set_hexpand(true);stack.set_vexpand(true);stack.add_named(&dashboard,Some("dashboard"));stack.add_named(&routing_page,Some("routing"));stack.add_named(&devices_page,Some("devices"));stack.add_named(&tools_page,Some("tools"));stack.add_named(&diagnostics,Some("diagnostics"));
    let brand=gtk::Box::new(Orientation::Vertical,1);brand.append(&gtk::Label::builder().label("MILMIT").halign(gtk::Align::Start).css_classes(["brand"]).build());brand.append(&gtk::Label::builder().label("SECURE CONTROL").halign(gtk::Align::Start).css_classes(["brand-sub"]).build());let n1=nav_button("◉   Dashboard");let n2=nav_button("⌁   Routing");let n3=nav_button("◇   Devices");let n4=nav_button("✦   Protection Tools");let n5=nav_button("≡   Diagnostics");n1.add_css_class("nav-active");let side=gtk::Box::new(Orientation::Vertical,9);side.add_css_class("sidebar");side.append(&brand);side.append(&gtk::Separator::new(Orientation::Horizontal));for n in [&n1,&n2,&n3,&n4,&n5]{side.append(n)}let sp=gtk::Box::new(Orientation::Vertical,0);sp.set_vexpand(true);side.append(&sp);side.append(&gtk::Label::builder().label("IKEv2 · strongSwan\nXFRM policy router\nIran-ready").halign(gtk::Align::Start).css_classes(["tiny"]).build());let shell=gtk::Box::new(Orientation::Horizontal,0);shell.add_css_class("shell");shell.append(&side);shell.append(&stack);let root=gtk::Box::new(Orientation::Vertical,0);root.append(&header);root.append(&shell);let window=adw::ApplicationWindow::builder().application(app).title("MilMit Secure").default_width(1040).default_height(820).content(&root).build();

    let navs=[n1.clone(),n2.clone(),n3.clone(),n4.clone(),n5.clone()];for (i,(btn,name)) in [(&n1,"dashboard"),(&n2,"routing"),(&n3,"devices"),(&n4,"tools"),(&n5,"diagnostics")].into_iter().enumerate(){let st=stack.clone();let ns=navs.clone();btn.connect_clicked(move |_|{st.set_visible_child_name(name);for (j,n) in ns.iter().enumerate(){if i==j{n.add_css_class("nav-active")}else{n.remove_css_class("nav-active")}}});}

    let (tx,rx)=mpsc::channel::<Event>();
    let status=Rc::new(status);let detail=Rc::new(detail);let status_icon=Rc::new(status_icon);let orb=Rc::new(orb);let spinner=Rc::new(spinner);let progress=Rc::new(progress);let connect=Rc::new(connect);let disconnect_btn=Rc::new(disconnect_btn);let ip_val=Rc::new(ip_val);let down_val=Rc::new(down_val);let up_val=Rc::new(up_val);let lat_val=Rc::new(lat_val);let health_score=Rc::new(health_score);let health_state=Rc::new(health_state);let buffer=Rc::new(buffer);
    let pulse=Rc::new(std::cell::Cell::new(false));{
        let status=Rc::clone(&status);let detail=Rc::clone(&detail);let status_icon=Rc::clone(&status_icon);let orb=Rc::clone(&orb);let spinner=Rc::clone(&spinner);let progress=Rc::clone(&progress);let connect=Rc::clone(&connect);let disconnect_btn=Rc::clone(&disconnect_btn);let ip_val=Rc::clone(&ip_val);let down_val=Rc::clone(&down_val);let up_val=Rc::clone(&up_val);let lat_val=Rc::clone(&lat_val);let health_score=Rc::clone(&health_score);let health_state=Rc::clone(&health_state);let buffer=Rc::clone(&buffer);let pulse=Rc::clone(&pulse);
        glib::timeout_add_local(Duration::from_millis(120),move||{if spinner.is_spinning(){progress.pulse()}down_val.set_label(&fmt_rate(live_value("RX_BPS")));up_val.set_label(&fmt_rate(live_value("TX_BPS")));let l=live_value("LATENCY_MS").unwrap_or_else(||"0".into());lat_val.set_label(if l=="0"{"— ms"}else{&format!("{l} ms")});while let Ok(e)=rx.try_recv(){match e{Event::Busy(m)=>{status.set_label(&m);detail.set_label("Negotiating tunnel and validating protected data path…");spinner.start();progress.set_visible(true);connect.set_sensitive(false);disconnect_btn.set_sensitive(false);orb.remove_css_class("orb-error");},Event::Log(t,b)=>{let mut it=buffer.end_iter();buffer.insert(&mut it,&format!("\n╭─ {t}\n{b}\n╰────────────────────────\n"));},Event::Connected(ip,label)=>{spinner.stop();progress.set_visible(false);status.set_label("Protected");detail.set_label(&label);status_icon.set_icon_name(Some("network-vpn-symbolic"));ip_val.set_label(&ip);orb.add_css_class("orb-ok");connect.set_visible(false);disconnect_btn.set_visible(true);connect.set_sensitive(true);disconnect_btn.set_sensitive(true);},Event::Disconnected=>{spinner.stop();progress.set_visible(false);status.set_label("Disconnected");detail.set_label("Network restored · ready");status_icon.set_icon_name(Some("network-offline-symbolic"));orb.remove_css_class("orb-ok");connect.set_visible(true);disconnect_btn.set_visible(false);connect.set_sensitive(true);disconnect_btn.set_sensitive(true);ip_val.set_label("—");},Event::Failed(m)=>{spinner.stop();progress.set_visible(false);status.set_label("Connection failed");detail.set_label("Backend recovered the route. Review Operation Monitor.");orb.add_css_class("orb-error");connect.set_visible(true);disconnect_btn.set_visible(false);connect.set_sensitive(true);disconnect_btn.set_sensitive(true);let mut it=buffer.end_iter();buffer.insert(&mut it,&format!("\nERROR\n{m}\n"));},Event::Tool(name,out)=>{if name=="Protection Health"{if let Some(n)=json_number(&out,"score"){health_score.set_label(&format!("{n}/100"));}if let Some(s)=json_string(&out,"state"){health_state.set_label(&s)}}let mut it=buffer.end_iter();buffer.insert(&mut it,&format!("\n╭─ {name}\n{out}\n╰────────────────────────\n"));},Event::PingResults(r)=>{let mut it=buffer.end_iter();buffer.insert(&mut it,&format!("\nLatency scan: {}/{} locations replied\n",r.iter().filter(|x|x.1.is_some()).count(),r.len()));}}}if pulse.get(){orb.add_css_class("orb-pulse")}else{orb.remove_css_class("orb-pulse")};glib::ControlFlow::Continue});
    }
    {let pulse=Rc::clone(&pulse);glib::timeout_add_local(Duration::from_millis(780),move||{pulse.set(!pulse.get());glib::ControlFlow::Continue});}

    {let tx=tx.clone();let user=user.clone();let pass=pass.clone();let location=location.clone();let mss=mss.clone();let dns=dns.clone();let hotspot=hotspot.clone();let iface=iface.clone();let vpn_macs=vpn_macs.clone();let direct_macs=direct_macs.clone();let recover=recover.clone();let kill=kill.clone();let routing=routing.clone();connect.connect_clicked(move |_|{let id=location.active_id().map(|s|s.to_string()).unwrap_or_else(||"ee-tll".into());let Some(sel)=by_id(&id)else{return};let username=user.text().trim().to_string();if username.is_empty(){let _=tx.send(Event::Failed("Surfshark service username is required under Routing.".into()));return}let password=pass.text().to_string();let s=AppSettings{mss:mss.value_as_int().clamp(900,1400)as u32,dns:if dns.text().trim().is_empty(){DEFAULT_DNS.into()}else{dns.text().trim().into()},hotspot_vpn:hotspot.is_active(),hotspot_iface:if iface.text().trim().is_empty(){"auto".into()}else{iface.text().trim().into()},recover_network:recover.is_active(),kill_switch:kill.is_active(),routing_mode:routing.active_id().map(|v|v.to_string()).unwrap_or_else(||"vpn_all".into()),hotspot_vpn_macs:normalize_mac_csv(vpn_macs.text().as_str()),hotspot_direct_macs:normalize_mac_csv(direct_macs.text().as_str())};save_username(&username);save_settings(&s);let tx=tx.clone();thread::spawn(move||{let candidates=restricted_candidates(sel.host);let _=tx.send(Event::Busy(format!("Connecting to {}…",sel.city)));for (i,ep) in candidates.iter().enumerate(){let _=tx.send(Event::Busy(format!("{} · route {}/{}",sel.city,i+1,candidates.len())));let(ok,log)=restricted_connect(ep,&username,&password,&s);let _=tx.send(Event::Log(format!("RESTRICTED ATTEMPT {}/{}",i+1,candidates.len()),log.clone()));if ok{let ip=parse_colon(&log,"Public IPv4").unwrap_or_else(||"connected".into());let country=parse_colon(&log,"Exit country").unwrap_or_default();let _=tx.send(Event::Connected(ip,format!("{} · {} · {}",sel.label,country,s.routing_mode)));let _=helper(&["save-lkg"]);return}}let _=disconnect();let _=tx.send(Event::Failed(format!("All {} restricted endpoints failed",candidates.len())));});});}
    {let tx=tx.clone();disconnect_btn.connect_clicked(move |_|{let tx=tx.clone();thread::spawn(move||{let _=tx.send(Event::Busy("Restoring network…".into()));let log=disconnect();let _=tx.send(Event::Log("DISCONNECT".into(),log));let _=tx.send(Event::Disconnected);});});}
    {let tx=tx.clone();scan.connect_clicked(move |_|{let tx=tx.clone();thread::spawn(move||{let _=tx.send(Event::PingResults(scan_latencies()));});});}
    {let tx=tx.clone();health_refresh.connect_clicked(move |_|{let tx=tx.clone();thread::spawn(move||{let o=helper(&["health"]);let _=tx.send(Event::Tool("Protection Health".into(),o));});});}
    for (button,cmd,label) in [(speed,"speed-test","Speed + TTFB"),(dns_test,"dns-test","DNS Evidence"),(mtu,"mtu-test","MTU/MSS Probe"),(save_lkg,"save-lkg","Last Known Good"),(support,"support-bundle","Support Bundle")]{let tx=tx.clone();button.connect_clicked(move |_|{let tx=tx.clone();thread::spawn(move||{let o=helper(&[cmd]);let _=tx.send(Event::Tool(label.into(),o));});});}
    {let tx=tx.clone();let route_target=route_target.clone();route_test.connect_clicked(move |_|{let t=route_target.text().trim().to_string();if t.is_empty(){return}let tx=tx.clone();thread::spawn(move||{let o=helper(&["route-test",&t]);let _=tx.send(Event::Tool("Route Tester".into(),o));});});}
    {let tx=tx.clone();recent.connect_clicked(move |_|{let tx=tx.clone();thread::spawn(move||{let o=helper(&["recent-destinations"]);let _=tx.send(Event::Tool("Recent Destinations".into(),o));});});}
    manage.connect_clicked(move |_|{let _=Command::new("python3").arg("/usr/lib/milmit-surfshark/hotspot-device-manager.py").spawn();});
    {let tx=tx.clone();emergency.connect_clicked(move |_|{let tx=tx.clone();thread::spawn(move||{let o=helper(&["emergency-stop"]);let _=tx.send(Event::Tool("EMERGENCY STOP".into(),o));let _=tx.send(Event::Disconnected);});});}
    {let tx=tx.clone();thread::spawn(move||{thread::sleep(Duration::from_millis(450));let o=helper(&["health"]);let _=tx.send(Event::Tool("Protection Health".into(),o));});}
    window.present();
}
