mod bundled_endpoints;
mod locations;

use adw::prelude::*;
use bundled_endpoints::for_host as bundled_for_host;
use gtk::{glib, Orientation};
use locations::{by_id, LOCATIONS};
use std::cell::RefCell;
use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::rc::Rc;
use std::thread;
use std::time::Duration;

const HELPER:&str="/usr/libexec/milmit-surfshark-helper";
const STATE:&str="/run/milmit-surfshark/restricted.state";
const LIVE:&str="/run/milmit-surfshark/live.state";
const DEFAULT_DNS:&str="162.252.172.57,149.154.159.92";

#[derive(Clone)]
struct Settings{mss:u32,dns:String,hotspot_vpn:bool,hotspot_iface:String,recover:bool,kill:bool,routing:String}
impl Default for Settings{fn default()->Self{Self{mss:1200,dns:DEFAULT_DNS.into(),hotspot_vpn:true,hotspot_iface:"auto".into(),recover:true,kill:true,routing:"vpn_all".into()}}}

fn cfg_dir()->PathBuf{std::env::var("XDG_CONFIG_HOME").map(PathBuf::from).or_else(|_|std::env::var("HOME").map(|h|PathBuf::from(h).join(".config"))).unwrap_or_else(|_|PathBuf::from(".")).join("milmit-surfshark")}
fn cfg_path()->PathBuf{cfg_dir().join("settings.conf")}
fn user_path()->PathBuf{cfg_dir().join("username")}
fn load_settings()->Settings{let mut s=Settings::default();if let Ok(t)=fs::read_to_string(cfg_path()){for l in t.lines(){if let Some((k,v))=l.split_once('='){match k{"mss"=>if let Ok(n)=v.parse(){s.mss=n},"dns"=>s.dns=v.into(),"hotspot_vpn"=>s.hotspot_vpn=v=="1","hotspot_iface"=>s.hotspot_iface=v.into(),"recover"=>s.recover=v=="1","kill"=>s.kill=v=="1","routing"=>s.routing=v.into(),_=>{}}}}}s}
fn save_settings(s:&Settings){let p=cfg_path();if let Some(d)=p.parent(){let _=fs::create_dir_all(d);}let _=fs::write(p,format!("mss={}\ndns={}\nhotspot_vpn={}\nhotspot_iface={}\nrecover={}\nkill={}\nrouting={}\n",s.mss,s.dns,s.hotspot_vpn as u8,s.hotspot_iface,s.recover as u8,s.kill as u8,s.routing));}
fn saved_user()->String{fs::read_to_string(user_path()).unwrap_or_default().trim().to_string()}
fn save_user(v:&str){let p=user_path();if let Some(d)=p.parent(){let _=fs::create_dir_all(d);}let _=fs::write(p,v);}
fn value(path:&str,key:&str)->Option<String>{let t=fs::read_to_string(path).ok()?;t.lines().find_map(|l|{let(k,v)=l.split_once('=')?;(k==key).then(||v.trim().to_string())})}
fn active()->bool{value(STATE,"VIRTUAL_IP").map(|v|Command::new("ip").args(["-4","addr","show"]).output().ok().map(|o|String::from_utf8_lossy(&o.stdout).contains(&v)).unwrap_or(false)).unwrap_or(false)}
fn helper(args:&[&str])->String{match Command::new("pkexec").arg(HELPER).args(args).output(){Ok(o)=>{let mut t=String::from_utf8_lossy(&o.stdout).to_string();t.push_str(&String::from_utf8_lossy(&o.stderr));t},Err(e)=>e.to_string()}}
fn candidate_ips(host:&str)->Vec<String>{let mut v=Vec::new();if host=="ee-tll.prod.surfshark.com"{v.push("185.174.159.123".into())}for x in bundled_for_host(host){if !v.iter().any(|e|e==x){v.push((*x).into())}}v}
fn connect_vpn(host:&str,user:&str,password:&str,s:&Settings)->(bool,String){let mut log=String::new();for ip in candidate_ips(host){let m=s.mss.to_string();let hotspot=if s.hotspot_vpn{"1"}else{"0"};let recover=if s.recover{"1"}else{"0"};let kill=if s.kill{"1"}else{"0"};let mut c=match Command::new("pkexec").arg(HELPER).args(["connect",&ip,user,&m,&s.dns,hotspot,recover,&s.hotspot_iface,kill,&s.routing,"","",host]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn(){Ok(c)=>c,Err(e)=>return(false,e.to_string())};if let Some(stdin)=c.stdin.as_mut(){let _=writeln!(stdin,"{password}");}match c.wait_with_output(){Ok(o)=>{let t=format!("{}{}",String::from_utf8_lossy(&o.stdout),String::from_utf8_lossy(&o.stderr));log.push_str(&format!("\n[{ip}]\n{t}\n"));if o.status.success()&&t.contains("Data-path test: OK"){return(true,log)}},Err(e)=>log.push_str(&format!("{e}\n"))}}(false,log)}

fn css(){let p=gtk::CssProvider::new();p.load_from_data(r#"
window{background:#192e45;color:#fff}.root{background:#192e45}.top{background:#17314d;padding:10px 14px;border-bottom:1px solid rgba(255,255,255,.06)}.brand{font-size:18px;font-weight:900}.caption{font-size:11px;color:#a8bacb}.page{padding:20px}.hero{padding:26px 20px;background:#213d59;border-radius:18px}.hero-title{font-size:28px;font-weight:900}.hero-sub{font-size:13px;color:#b9c9d7}.shield{min-width:118px;min-height:118px;border-radius:999px;background:#294d6d;border:3px solid #4f7698}.shield-on{background:#1f694f;border-color:#5bd39a}.shield-busy{background:#7a5c20;border-color:#e8bd57}.big-icon{-gtk-icon-size:52px}.primary{min-height:50px;border-radius:10px;background:#57c28b;color:#082317;font-weight:900}.primary:hover{background:#68d69c}.danger{min-height:50px;border-radius:10px;background:#c94d5b;color:#fff;font-weight:900}.location{min-height:64px;border-radius:12px;background:#27435f;border:1px solid rgba(255,255,255,.06);padding:0 14px}.location:hover{background:#2d4b68}.row{min-height:54px;background:#223d58;border-bottom:1px solid rgba(255,255,255,.06);padding:0 14px}.row-first{border-radius:12px 12px 0 0}.row-last{border-radius:0 0 12px 12px;border-bottom:none}.row-single{border-radius:12px;border-bottom:none}.row-title{font-size:14px;font-weight:700}.row-sub{font-size:11px;color:#a9bac9}.section{font-size:12px;font-weight:800;color:#a9bac9;margin-top:8px}.back{background:transparent;box-shadow:none}.pill{background:#2b4b68;border-radius:999px;padding:6px 10px;font-size:11px}.ok{color:#67d99f}.warn{color:#f3c65d}.diag{background:#11273b;border-radius:12px;padding:12px;font-family:monospace;font-size:11px}entry,spinbutton,combobox button{min-height:42px;border-radius:9px;background:#203a54}switch{margin:6px}.stack{background:#192e45}.separator{background:rgba(255,255,255,.08);min-height:1px}
"#);if let Some(d)=gtk::gdk::Display::default(){gtk::style_context_add_provider_for_display(&d,&p,gtk::STYLE_PROVIDER_PRIORITY_APPLICATION)}}
fn title_box(t:&str,s:&str)->gtk::Box{let b=gtk::Box::new(Orientation::Vertical,2);b.append(&gtk::Label::builder().label(t).halign(gtk::Align::Start).css_classes(["row-title"]).build());if !s.is_empty(){b.append(&gtk::Label::builder().label(s).halign(gtk::Align::Start).wrap(true).css_classes(["row-sub"]).build())}b}
fn page_header(stack:&gtk::Stack,title:&str)->gtk::Box{let b=gtk::Box::new(Orientation::Horizontal,8);b.add_css_class("top");let back=gtk::Button::from_icon_name("go-previous-symbolic");back.add_css_class("back");let st=stack.clone();back.connect_clicked(move |_|st.set_visible_child_name("home"));b.append(&back);b.append(&gtk::Label::builder().label(title).hexpand(true).halign(gtk::Align::Start).css_classes(["brand"]).build());b}
fn nav_row(title:&str,sub:&str)->(gtk::Button,gtk::Box){let button=gtk::Button::new();button.add_css_class("row");button.set_hexpand(true);let row=gtk::Box::new(Orientation::Horizontal,10);row.append(&title_box(title,sub));let spacer=gtk::Box::new(Orientation::Horizontal,0);spacer.set_hexpand(true);row.append(&spacer);row.append(&gtk::Image::from_icon_name("go-next-symbolic"));button.set_child(Some(&row));let wrap=gtk::Box::new(Orientation::Vertical,0);wrap.append(&button);(button,wrap)}
fn switch_row(title:&str,sub:&str,on:bool)->(gtk::Box,gtk::Switch){let row=gtk::Box::new(Orientation::Horizontal,10);row.add_css_class("row");row.append(&title_box(title,sub));let spacer=gtk::Box::new(Orientation::Horizontal,0);spacer.set_hexpand(true);row.append(&spacer);let sw=gtk::Switch::builder().active(on).valign(gtk::Align::Center).build();row.append(&sw);(row,sw)}

fn main()->glib::ExitCode{let app=adw::Application::builder().application_id("net.milmit.SurfsharkIkev2").build();app.connect_activate(build);app.run()}
fn build(app:&adw::Application){css();let settings=Rc::new(RefCell::new(load_settings()));let selected=Rc::new(RefCell::new("ee-tll".to_string()));let stack=gtk::Stack::new();stack.add_css_class("stack");stack.set_transition_type(gtk::StackTransitionType::SlideLeftRight);stack.set_transition_duration(220);

let root=gtk::Box::new(Orientation::Vertical,0);root.add_css_class("root");let top=gtk::Box::new(Orientation::Horizontal,10);top.add_css_class("top");let brand=gtk::Label::builder().label("MilMit Secure").halign(gtk::Align::Start).css_classes(["brand"]).build();top.append(&brand);let spacer=gtk::Box::new(Orientation::Horizontal,0);spacer.set_hexpand(true);top.append(&spacer);let settings_btn=gtk::Button::from_icon_name("emblem-system-symbolic");settings_btn.add_css_class("back");top.append(&settings_btn);root.append(&top);

let home=gtk::Box::new(Orientation::Vertical,16);home.add_css_class("page");let on=active();let shield=gtk::Box::new(Orientation::Vertical,0);shield.add_css_class("shield");if on{shield.add_css_class("shield-on")}shield.set_halign(gtk::Align::Center);shield.set_valign(gtk::Align::Center);let icon=gtk::Image::from_icon_name(if on{"network-vpn-symbolic"}else{"network-offline-symbolic"});icon.add_css_class("big-icon");shield.append(&icon);let status=gtk::Label::builder().label(if on{"SECURE CONNECTION"}else{"UNSECURED CONNECTION"}).css_classes(["hero-title"]).build();let status_sub=gtk::Label::builder().label(if on{"Your traffic is protected"}else{"Connect to protect your traffic"}).css_classes(["hero-sub"]).build();let hero=gtk::Box::new(Orientation::Vertical,10);hero.add_css_class("hero");hero.append(&shield);hero.append(&status);hero.append(&status_sub);home.append(&hero);
let loc_btn=gtk::Button::new();loc_btn.add_css_class("location");let locrow=gtk::Box::new(Orientation::Horizontal,10);let loclabel=gtk::Label::builder().label("🇪🇪 Estonia · Tallinn").hexpand(true).halign(gtk::Align::Start).css_classes(["row-title"]).build();locrow.append(&gtk::Image::from_icon_name("find-location-symbolic"));locrow.append(&loclabel);locrow.append(&gtk::Image::from_icon_name("go-next-symbolic"));loc_btn.set_child(Some(&locrow));home.append(&loc_btn);
let connect=gtk::Button::with_label(if on{"Disconnect"}else{"Secure my connection"});connect.add_css_class(if on{"danger"}else{"primary"});home.append(&connect);
let metrics=gtk::Box::new(Orientation::Horizontal,8);for (k,v) in [("IP",value(STATE,"PUBLIC_IP").unwrap_or_else(||"—".into())),("EXIT",value(STATE,"EXIT_COUNTRY").unwrap_or_else(||"—".into())),("PING",value(LIVE,"LATENCY_MS").map(|x|format!("{x} ms")).unwrap_or_else(||"—".into()))]{let c=gtk::Box::new(Orientation::Vertical,2);c.set_hexpand(true);c.add_css_class("pill");c.append(&gtk::Label::builder().label(v).css_classes(["row-title"]).build());c.append(&gtk::Label::builder().label(k).css_classes(["row-sub"]).build());metrics.append(&c)}home.append(&metrics);stack.add_named(&home,Some("home"));

let locations_page=gtk::Box::new(Orientation::Vertical,0);locations_page.append(&page_header(&stack,"Select location"));let locbody=gtk::Box::new(Orientation::Vertical,10);locbody.add_css_class("page");let search=gtk::SearchEntry::builder().placeholder_text("Search country or city").build();locbody.append(&search);let list=gtk::ListBox::new();list.set_selection_mode(gtk::SelectionMode::None);let mut filters:Vec<(gtk::ListBoxRow,String)>=Vec::new();for l in LOCATIONS{let row=gtk::ListBoxRow::new();let btn=gtk::Button::new();btn.add_css_class("row");let h=gtk::Box::new(Orientation::Horizontal,10);h.append(&title_box(l.country,l.city));let sp=gtk::Box::new(Orientation::Horizontal,0);sp.set_hexpand(true);h.append(&sp);h.append(&gtk::Image::from_icon_name("go-next-symbolic"));btn.set_child(Some(&h));let id=l.id.to_string();let label=l.label.to_string();let st=stack.clone();let sel=selected.clone();let ll=loclabel.clone();btn.connect_clicked(move |_|{*sel.borrow_mut()=id.clone();ll.set_label(&label);st.set_visible_child_name("home")});row.set_child(Some(&btn));list.append(&row);filters.push((row,format!("{} {} {}",l.country,l.city,l.label).to_lowercase()))}let filters=Rc::new(filters);let ff=filters.clone();search.connect_search_changed(move |e|{let q=e.text().to_lowercase();for(row,text)in ff.iter(){row.set_visible(q.is_empty()||text.contains(&q))}});let sc=gtk::ScrolledWindow::builder().child(&list).vexpand(true).build();locbody.append(&sc);locations_page.append(&locbody);stack.add_named(&locations_page,Some("locations"));

let settings_page=gtk::Box::new(Orientation::Vertical,0);settings_page.append(&page_header(&stack,"Settings"));let sb=gtk::Box::new(Orientation::Vertical,12);sb.add_css_class("page");sb.append(&gtk::Label::builder().label("VPN SETTINGS").halign(gtk::Align::Start).css_classes(["section"]).build());let(vpnrow,vpnwrap)=nav_row("VPN settings","Kill switch, Iran bypass, DNS and transport");sb.append(&vpnwrap);let(splitrow,splitwrap)=nav_row("Split tunneling","Iran bypass and manual Direct / VPN / Block policies");sb.append(&splitwrap);let(devrow,devwrap)=nav_row("Hotspot & devices","Per-device routes, quota, speed limit and guest hotspot");sb.append(&devwrap);sb.append(&gtk::Label::builder().label("TOOLS").halign(gtk::Align::Start).css_classes(["section"]).build());let(toolsrow,toolswrap)=nav_row("Advanced tools","Health, safe apply, route explain and diagnostics");sb.append(&toolswrap);let(diagrow,diagwrap)=nav_row("Diagnostics","Live backend output and support tools");sb.append(&diagwrap);settings_page.append(&sb);stack.add_named(&settings_page,Some("settings"));

let vpn_page=gtk::Box::new(Orientation::Vertical,0);vpn_page.append(&page_header(&stack,"VPN settings"));let vb=gtk::Box::new(Orientation::Vertical,10);vb.add_css_class("page");let(krow,ksw)=switch_row("Kill switch","Block unprotected traffic when the VPN path fails",settings.borrow().kill);vb.append(&krow);let(rrow,rsw)=switch_row("Bypass Iranian destinations","Iranian IP ranges go direct; foreign traffic stays protected",settings.borrow().routing=="iran_direct");vb.append(&rrow);let(recrow,recsw)=switch_row("Auto recovery","Watchdog repairs the tunnel automatically",settings.borrow().recover);vb.append(&recrow);let dns=gtk::Entry::builder().text(&settings.borrow().dns).placeholder_text("VPN DNS servers").build();vb.append(&title_box("DNS servers","Comma-separated IPv4 addresses"));vb.append(&dns);let mss=gtk::SpinButton::with_range(900.0,1400.0,10.0);mss.set_value(settings.borrow().mss as f64);vb.append(&title_box("TCP MSS","Restricted-network packet clamp"));vb.append(&mss);let savevpn=gtk::Button::with_label("Save VPN settings");savevpn.add_css_class("primary");vb.append(&savevpn);let update_rules=gtk::Button::with_label("Update Iran rules now");update_rules.add_css_class("location");vb.append(&update_rules);vpn_page.append(&vb);stack.add_named(&vpn_page,Some("vpn"));

let split_page=gtk::Box::new(Orientation::Vertical,0);split_page.append(&page_header(&stack,"Split tunneling"));let spb=gtk::Box::new(Orientation::Vertical,10);spb.add_css_class("page");spb.append(&title_box("Iran bypass","Built-in local-first Iranian CIDR rules. Priority: Block > Force VPN > Manual Direct > Iran Direct > Default."));let explain=gtk::Entry::builder().placeholder_text("Domain or IP to explain, e.g. digikala.com").build();spb.append(&explain);let explain_btn=gtk::Button::with_label("Explain route");explain_btn.add_css_class("location");spb.append(&explain_btn);let target=gtk::Entry::builder().placeholder_text("Domain / IP / CIDR").build();spb.append(&target);let acts=gtk::Box::new(Orientation::Horizontal,6);for(a,label)in[("direct","Bypass VPN"),("vpn","Force VPN"),("block","Block")]{let b=gtk::Button::with_label(label);b.set_hexpand(true);let t=target.clone();b.connect_clicked(move |_|{let v=t.text().to_string();if !v.is_empty(){let _=helper(&["policy-add",&v,a,"both"]);}});acts.append(&b)}spb.append(&acts);let cand=gtk::Button::with_label("Recent destinations / candidates");cand.add_css_class("location");spb.append(&cand);split_page.append(&spb);stack.add_named(&split_page,Some("split"));

let dev_page=gtk::Box::new(Orientation::Vertical,0);dev_page.append(&page_header(&stack,"Hotspot & devices"));let db=gtk::Box::new(Orientation::Vertical,10);db.add_css_class("page");db.append(&title_box("Hotspot routing","Share the protected tunnel with phones and other devices."));let repair=gtk::Button::with_label("Repair hotspot routing");repair.add_css_class("primary");db.append(&repair);let manager=gtk::Button::with_label("Open visual device manager");manager.add_css_class("location");db.append(&manager);let guest=gtk::Button::with_label("Start 60-minute Guest Hotspot");guest.add_css_class("location");db.append(&guest);let force_dns=gtk::CheckButton::with_label("Force VPN DNS for hotspot clients");force_dns.set_active(true);let quic=gtk::CheckButton::with_label("Block QUIC (UDP/443)");let isolation=gtk::CheckButton::with_label("Client isolation");let ipv6=gtk::CheckButton::with_label("Block hotspot IPv6 leaks");ipv6.set_active(true);db.append(&force_dns);db.append(&quic);db.append(&isolation);db.append(&ipv6);let applydev=gtk::Button::with_label("Apply hotspot protection");applydev.add_css_class("primary");db.append(&applydev);dev_page.append(&db);stack.add_named(&dev_page,Some("devices"));

let tools_page=gtk::Box::new(Orientation::Vertical,0);tools_page.append(&page_header(&stack,"Advanced tools"));let tb=gtk::Box::new(Orientation::Vertical,8);tb.add_css_class("page");for(cmd,label)in[("health","Protection health"),("apply-safe","Apply safely + rollback"),("full-live-test","Full live test"),("speed-test","Speed & TTFB"),("dns-test","DNS evidence"),("mtu-test","MTU / MSS probe"),("save-lkg","Save Last Known Good"),("rules-status","Iran rules status"),("support-bundle","Create support bundle")]{let b=gtk::Button::with_label(label);b.add_css_class("location");b.connect_clicked(move |_|{let _=helper(&[cmd]);});tb.append(&b)}let emergency=gtk::Button::with_label("Emergency stop & network recovery");emergency.add_css_class("danger");emergency.connect_clicked(|_|{let _=helper(&["emergency-stop"]);});tb.append(&emergency);let tscroll=gtk::ScrolledWindow::builder().child(&tb).vexpand(true).build();tools_page.append(&tscroll);stack.add_named(&tools_page,Some("tools"));

let diag_page=gtk::Box::new(Orientation::Vertical,0);diag_page.append(&page_header(&stack,"Diagnostics"));let dig=gtk::Box::new(Orientation::Vertical,10);dig.add_css_class("page");let text=gtk::TextView::builder().editable(false).monospace(true).wrap_mode(gtk::WrapMode::WordChar).css_classes(["diag"]).vexpand(true).build();let buf=text.buffer();buf.set_text("MilMit Secure diagnostics\n");let refresh=gtk::Button::with_label("Refresh diagnostics");refresh.add_css_class("location");let b2=buf.clone();refresh.connect_clicked(move |_|{let mut out=String::new();out.push_str(&helper(&["watchdog-status"]));out.push_str("\n\n--- Router ---\n");out.push_str(&helper(&["router-status"]));out.push_str("\n\n--- Live test ---\n");out.push_str(&helper(&["full-live-test"]));b2.set_text(&out)});dig.append(&refresh);dig.append(&gtk::ScrolledWindow::builder().child(&text).vexpand(true).build());diag_page.append(&dig);stack.add_named(&diag_page,Some("diagnostics"));

let st=stack.clone();settings_btn.connect_clicked(move |_|st.set_visible_child_name("settings"));let st=stack.clone();loc_btn.connect_clicked(move |_|st.set_visible_child_name("locations"));for(btn,name)in[(vpnrow,"vpn"),(splitrow,"split"),(devrow,"devices"),(toolsrow,"tools"),(diagrow,"diagnostics")]{let st=stack.clone();btn.connect_clicked(move |_|st.set_visible_child_name(name));}

let settings_save=settings.clone();savevpn.connect_clicked(move |_|{let mut s=settings_save.borrow_mut();s.kill=ksw.is_active();s.recover=recsw.is_active();s.routing=if rsw.is_active(){"iran_direct".into()}else{"vpn_all".into()};s.dns=dns.text().to_string();s.mss=mss.value() as u32;save_settings(&s)});update_rules.connect_clicked(|_|{let _=helper(&["rules-update"]);});explain_btn.connect_clicked(move |_|{let v=explain.text().to_string();if !v.is_empty(){let _=helper(&["route-explain",&v]);}});cand.connect_clicked(|_|{let _=helper(&["candidates"]);});repair.connect_clicked(|_|{let _=helper(&["hotspot-repair"]);});manager.connect_clicked(|_|{let _=Command::new("pkexec").args([HELPER,"router-status"]).spawn();});guest.connect_clicked(|_|{let _=helper(&["guest-start","60","MilMit Guest"]);});applydev.connect_clicked(move |_|{let _=helper(&["router-options",if force_dns.is_active(){"1"}else{"0"},if quic.is_active(){"1"}else{"0"},if isolation.is_active(){"1"}else{"0"},if ipv6.is_active(){"block"}else{"allow"}]);});

let appwin=adw::ApplicationWindow::builder().application(app).title("MilMit Secure").default_width(430).default_height(760).resizable(true).build();root.append(&stack);appwin.set_content(Some(&root));appwin.present();

let settings_conn=settings.clone();let sel_conn=selected.clone();let status_c=status.clone();let sub_c=status_sub.clone();let shield_c=shield.clone();let connect_c=connect.clone();connect.connect_clicked(move |_|{if active(){let _=helper(&["disconnect"]);status_c.set_label("UNSECURED CONNECTION");sub_c.set_label("Connect to protect your traffic");shield_c.remove_css_class("shield-on");connect_c.set_label("Secure my connection");connect_c.remove_css_class("danger");connect_c.add_css_class("primary");return}let user=saved_user();if user.is_empty(){status_c.set_label("ADD CREDENTIALS");sub_c.set_label("Open Settings and save your Surfshark service username first");return}let id=sel_conn.borrow().clone();let Some(loc)=by_id(&id)else{return};status_c.set_label("CONNECTING…");sub_c.set_label(&format!("Securing via {}",loc.label));shield_c.add_css_class("shield-busy");let s=settings_conn.borrow().clone();let host=loc.host.to_string();let status2=status_c.clone();let sub2=sub_c.clone();let shield2=shield_c.clone();let button2=connect_c.clone();let (tx,rx)=std::sync::mpsc::channel();thread::spawn(move ||{let r=connect_vpn(&host,&user,"",&s);let _=tx.send(r);});glib::timeout_add_local(Duration::from_millis(150),move ||match rx.try_recv(){Ok((ok,_log))=>{shield2.remove_css_class("shield-busy");if ok{shield2.add_css_class("shield-on");status2.set_label("SECURE CONNECTION");sub2.set_label("Your traffic is protected");button2.set_label("Disconnect");button2.remove_css_class("primary");button2.add_css_class("danger")}else{status2.set_label("CONNECTION FAILED");sub2.set_label("Open Diagnostics for details")}glib::ControlFlow::Break},Err(std::sync::mpsc::TryRecvError::Empty)=>glib::ControlFlow::Continue,Err(_)=>glib::ControlFlow::Break});});

// Credentials are deliberately kept on a dedicated small modal-like page.
let cred_page=gtk::Box::new(Orientation::Vertical,0);cred_page.append(&page_header(&stack,"Credentials"));let cb=gtk::Box::new(Orientation::Vertical,10);cb.add_css_class("page");let username=gtk::Entry::builder().text(&saved_user()).placeholder_text("Surfshark service username").build();let password=gtk::PasswordEntry::builder().placeholder_text("Service password · blank uses saved password").show_peek_icon(true).build();cb.append(&title_box("Surfshark service credentials","Saved password is stored only by the privileged root helper."));cb.append(&username);cb.append(&password);let savecred=gtk::Button::with_label("Save credentials securely");savecred.add_css_class("primary");cb.append(&savecred);cred_page.append(&cb);stack.add_named(&cred_page,Some("credentials"));let(credrow,credwrap)=nav_row("Credentials","Surfshark service username and password");sb.prepend(&credwrap);let st=stack.clone();credrow.connect_clicked(move |_|st.set_visible_child_name("credentials"));savecred.connect_clicked(move |_|{let u=username.text().to_string();if u.is_empty(){return}save_user(&u);let p=password.text().to_string();if !p.is_empty(){let mut c=match Command::new("pkexec").arg(HELPER).args(["connect","0.0.0.0",&u,"1200",DEFAULT_DNS,"1","1","auto","1","vpn_all","","","ee-tll.prod.surfshark.com"]).stdin(Stdio::piped()).stdout(Stdio::null()).stderr(Stdio::null()).spawn(){Ok(c)=>c,Err(_)=>return};if let Some(stdin)=c.stdin.as_mut(){let _=writeln!(stdin,"{p}");}let _=c.kill();}});
}
